export const englishCountries = [
  { name: 'Afghanistan' },
  { name: 'Åland Islands' },
  { name: 'Albania' },
  { name: 'Algeria' },
  { name: 'American Samoa' },
  { name: 'AndorrA' },
  { name: 'Angola' },
  { name: 'Anguilla' },
  { name: 'Antarctica' },
  { name: 'Antigua and Barbuda' },
  { name: 'Argentina' },
  { name: 'Armenia' },
  { name: 'Aruba' },
  { name: 'Australia' },
  { name: 'Austria' },
  { name: 'Azerbaijan' },
  { name: 'Bahamas' },
  { name: 'Bahrain' },
  { name: 'Bangladesh' },
  { name: 'Barbados' },
  { name: 'Belarus' },
  { name: 'Belgium' },
  { name: 'Belize' },
  { name: 'Benin' },
  { name: 'Bermuda' },
  { name: 'Bhutan' },
  { name: 'Bolivia' },
  { name: 'Bosnia and Herzegovina' },
  { name: 'Botswana' },
  { name: 'Bouvet Island' },
  { name: 'Brazil' },
  { name: 'British Indian Ocean Territory' },
  { name: 'Brunei Darussalam' },
  { name: 'Bulgaria' },
  { name: 'Burkina Faso' },
  { name: 'Burundi' },
  { name: 'Cambodia' },
  { name: 'Cameroon' },
  { name: 'Canada' },
  { name: 'Cape Verde' },
  { name: 'Cayman Islands' },
  { name: 'Central African Republic' },
  { name: 'Chad' },
  { name: 'Chile' },
  { name: 'China' },
  { name: 'Christmas Island' },
  { name: 'Cocos (Keeling) Islands' },
  { name: 'Colombia' },
  { name: 'Comoros' },
  { name: 'Congo' },
  { name: 'Congo, The Democratic Republic of the' },
  { name: 'Cook Islands' },
  { name: 'Costa Rica' },
  { name: 'Cote D\'Ivoire' },
  { name: 'Croatia' },
  { name: 'Cuba' },
  { name: 'Cyprus' },
  { name: 'Czech Republic' },
  { name: 'Denmark' },
  { name: 'Djibouti' },
  { name: 'Dominica' },
  { name: 'Dominican Republic' },
  { name: 'Ecuador' },
  { name: 'Egypt' },
  { name: 'El Salvador' },
  { name: 'Equatorial Guinea' },
  { name: 'Eritrea' },
  { name: 'Estonia' },
  { name: 'Ethiopia' },
  { name: 'Falkland Islands (Malvinas)' },
  { name: 'Faroe Islands' },
  { name: 'Fiji' },
  { name: 'Finland' },
  { name: 'France' },
  { name: 'French Guiana' },
  { name: 'French Polynesia' },
  { name: 'French Southern Territories' },
  { name: 'Gabon' },
  { name: 'Gambia' },
  { name: 'Georgia' },
  { name: 'Germany' },
  { name: 'Ghana' },
  { name: 'Gibraltar' },
  { name: 'Greece' },
  { name: 'Greenland' },
  { name: 'Grenada' },
  { name: 'Guadeloupe' },
  { name: 'Guam' },
  { name: 'Guatemala' },
  { name: 'Guernsey' },
  { name: 'Guinea' },
  { name: 'Guinea-Bissau' },
  { name: 'Guyana' },
  { name: 'Haiti' },
  { name: 'Heard Island and Mcdonald Islands' },
  { name: 'Holy See (Vatican City State)' },
  { name: 'Honduras' },
  { name: 'Hong Kong' },
  { name: 'Hungary' },
  { name: 'Iceland' },
  { name: 'India' },
  { name: 'Indonesia' },
  { name: 'Iran, Islamic Republic Of' },
  { name: 'Iraq' },
  { name: 'Ireland' },
  { name: 'Isle of Man' },
  { name: 'Israel' },
  { name: 'Italy' },
  { name: 'Jamaica' },
  { name: 'Japan' },
  { name: 'Jersey' },
  { name: 'Jordan' },
  { name: 'Kazakhstan' },
  { name: 'Kenya' },
  { name: 'Kiribati' },
  { name: 'Korea, Democratic People\'S Republic of' },
  { name: 'Korea, Republic of' },
  { name: 'Kuwait' },
  { name: 'Kyrgyzstan' },
  { name: 'Lao People\'S Democratic Republic' },
  { name: 'Latvia' },
  { name: 'Lebanon' },
  { name: 'Lesotho' },
  { name: 'Liberia' },
  { name: 'Libyan Arab Jamahiriya' },
  { name: 'Liechtenstein' },
  { name: 'Lithuania' },
  { name: 'Luxembourg' },
  { name: 'Macao' },
  { name: 'Macedonia, The Former Yugoslav Republic of' },
  { name: 'Madagascar' },
  { name: 'Malawi' },
  { name: 'Malaysia' },
  { name: 'Maldives' },
  { name: 'Mali' },
  { name: 'Malta' },
  { name: 'Marshall Islands' },
  { name: 'Martinique' },
  { name: 'Mauritania' },
  { name: 'Mauritius' },
  { name: 'Mayotte' },
  { name: 'Mexico' },
  { name: 'Micronesia, Federated States of' },
  { name: 'Moldova, Republic of' },
  { name: 'Monaco' },
  { name: 'Mongolia' },
  { name: 'Montserrat' },
  { name: 'Morocco' },
  { name: 'Mozambique' },
  { name: 'Myanmar' },
  { name: 'Namibia' },
  { name: 'Nauru' },
  { name: 'Nepal' },
  { name: 'Netherlands' },
  { name: 'Netherlands Antilles' },
  { name: 'New Caledonia' },
  { name: 'New Zealand' },
  { name: 'Nicaragua' },
  { name: 'Niger' },
  { name: 'Nigeria' },
  { name: 'Niue' },
  { name: 'Norfolk Island' },
  { name: 'Northern Mariana Islands' },
  { name: 'Norway' },
  { name: 'Oman' },
  { name: 'Pakistan' },
  { name: 'Palau' },
  { name: 'Palestinian Territory, Occupied' },
  { name: 'Panama' },
  { name: 'Papua New Guinea' },
  { name: 'Paraguay' },
  { name: 'Peru' },
  { name: 'Philippines' },
  { name: 'Pitcairn' },
  { name: 'Poland' },
  { name: 'Portugal' },
  { name: 'Puerto Rico' },
  { name: 'Qatar' },
  { name: 'Reunion' },
  { name: 'Romania' },
  { name: 'Russian Federation' },
  { name: 'RWANDA' },
  { name: 'Saint Helena' },
  { name: 'Saint Kitts and Nevis' },
  { name: 'Saint Lucia' },
  { name: 'Saint Pierre and Miquelon' },
  { name: 'Saint Vincent and the Grenadines' },
  { name: 'Samoa' },
  { name: 'San Marino' },
  { name: 'Sao Tome and Principe' },
  { name: 'Saudi Arabia' },
  { name: 'Senegal' },
  { name: 'Serbia and Montenegro' },
  { name: 'Seychelles' },
  { name: 'Sierra Leone' },
  { name: 'Singapore' },
  { name: 'Slovakia' },
  { name: 'Slovenia' },
  { name: 'Solomon Islands' },
  { name: 'Somalia' },
  { name: 'South Africa' },
  { name: 'South Georgia and the South Sandwich Islands' },
  { name: 'Spain' },
  { name: 'Sri Lanka' },
  { name: 'Sudan' },
  { name: 'Suri name' },
  { name: 'Svalbard and Jan Mayen' },
  { name: 'Swaziland' },
  { name: 'Sweden' },
  { name: 'Switzerland' },
  { name: 'Syrian Arab Republic' },
  { name: 'Taiwan, Province of China' },
  { name: 'Tajikistan' },
  { name: 'Tanzania, United Republic of' },
  { name: 'Thailand' },
  { name: 'Timor-Leste' },
  { name: 'Togo' },
  { name: 'Tokelau' },
  { name: 'Tonga' },
  { name: 'Trinidad and Tobago' },
  { name: 'Tunisia' },
  { name: 'Turkey' },
  { name: 'Turkmenistan' },
  { name: 'Turks and Caicos Islands' },
  { name: 'Tuvalu' },
  { name: 'Uganda' },
  { name: 'Ukraine' },
  { name: 'United Arab Emirates' },
  { name: 'United Kingdom' },
  { name: 'United States' },
  { name: 'United States Minor Outlying Islands' },
  { name: 'Uruguay' },
  { name: 'Uzbekistan' },
  { name: 'Vanuatu' },
  { name: 'Venezuela' },
  { name: 'Viet Nam' },
  { name: 'Virgin Islands, British' },
  { name: 'Virgin Islands, U.S.' },
  { name: 'Wallis and Futuna' },
  { name: 'Western Sahara' },
  { name: 'Yemen' },
  { name: 'Zambia' },
  { name: 'Zimbabwe' }
]

export const lithuanianCountries = [
  { name: 'Abchazija' },
  { name: 'Afganistanas' },
  { name: 'Airija' },
  { name: 'Alandai' },
  { name: 'Albanija' },
  { name: 'Alžyras' },
  { name: 'Amerikos Samoa' },
  { name: 'Andora' },
  { name: 'Angilija' },
  { name: 'Angola' },
  { name: 'Antarktida' },
  { name: 'Antigva ir Barbuda' },
  { name: 'Argentina' },
  { name: 'Armėnija' },
  { name: 'Aruba' },
  { name: 'Australija' },
  { name: 'Austrija' },
  { name: 'Azerbaidžanas' },
  { name: 'Azorai' },
  { name: 'Bahamos' },
  { name: 'Bahreinas' },
  { name: 'Baltarusija' },
  { name: 'Bangladešas' },
  { name: 'Barbadosas' },
  { name: 'Belgija' },
  { name: 'Belizas' },
  { name: 'Beninas' },
  { name: 'Bermuda' },
  { name: 'Bisau Gvinėja' },
  { name: 'Bolivija' },
  { name: 'Bosnija ir Hercegovina' },
  { name: 'Botsvana' },
  { name: 'Brazilija' },
  { name: 'Brunėjus' },
  { name: 'Bulgarija' },
  { name: 'Burkina Fasas' },
  { name: 'Burundis' },
  { name: 'Buvė' },
  { name: 'Butanas' },
  { name: 'Centrinės Afrikos Respublika' },
  { name: 'Čadas' },
  { name: 'Čekija' },
  { name: 'Čilė' },
  { name: 'Danija' },
  { name: 'Didžiosios Britanijos Mergelių salos' },
  { name: 'Dominika' },
  { name: 'Dominikos Respublika' },
  { name: 'Dramblio Kaulo Krantas' },
  { name: 'Džersis' },
  { name: 'Džibutis' },
  { name: 'Egiptas' },
  { name: 'Ekvadoras' },
  { name: 'Eritrėja' },
  { name: 'Estija' },
  { name: 'Etiopija' },
  { name: 'Falklando salos' },
  { name: 'Farerų salos' },
  { name: 'Fidžis' },
  { name: 'Filipinai' },
  { name: 'Gabonas' },
  { name: 'Gajana' },
  { name: 'Gambija' },
  { name: 'Gana' },
  { name: 'Gernsis' },
  { name: 'Gibraltaras' },
  { name: 'Graikija' },
  { name: 'Grenada' },
  { name: 'Grenlandija' },
  { name: 'Gruzija' },
  { name: 'Guamas' },
  { name: 'Gvadelupa' },
  { name: 'Gvatemala' },
  { name: 'Gvinėja' },
  { name: 'Haitis' },
  { name: 'Herdo ir Makdonaldo salos' },
  { name: 'Hondūras' },
  { name: 'Honkongas' },
  { name: 'Indija' },
  { name: 'Indijos vandenyno britų salos' },
  { name: 'Indonezija' },
  { name: 'Irakas' },
  { name: 'Iranas' },
  { name: 'Islandija' },
  { name: 'Ispanija' },
  { name: 'Italija' },
  { name: 'Izraelis' },
  { name: 'Jamaika' },
  { name: 'Japonija' },
  { name: 'Jemenas' },
  { name: 'Jordanija' },
  { name: 'Jungtiniai Arabų Emyratai' },
  { name: 'Jungtinė Karalystė' },
  { name: 'JAV' },
  { name: 'Juodkalnija' },
  { name: 'Kaimanų salos' },
  { name: 'Kalėdų sala' },
  { name: 'Kalnų Karabachas' },
  { name: 'Kambodža' },
  { name: 'Kamerūnas' },
  { name: 'Kanada' },
  { name: 'Kataras' },
  { name: 'Kazachija' },
  { name: 'Kenija' },
  { name: 'Kinija' },
  { name: 'Kipras' },
  { name: 'Kirgizija' },
  { name: 'Kiribatis' },
  { name: 'Kokosų salos' },
  { name: 'Kolumbija' },
  { name: 'Komorai' },
  { name: 'Kongo Demokratinė Respublika' },
  { name: 'Kongas' },
  { name: 'Kosovas' },
  { name: 'Kosta Rika' },
  { name: 'Kroatija' },
  { name: 'Kuba' },
  { name: 'Kuko salos' },
  { name: 'Kuveitas' },
  { name: 'Laosas' },
  { name: 'Latvija' },
  { name: 'Lenkija' },
  { name: 'Lesotas' },
  { name: 'Libanas' },
  { name: 'Liberija' },
  { name: 'Libija' },
  { name: 'Lichtenšteinas' },
  { name: 'Lietuva' },
  { name: 'Liuksemburgas' },
  { name: 'Majotas' },
  { name: 'Makao' },
  { name: 'Madagaskaras' },
  { name: 'Makedonija' },
  { name: 'Malaizija' },
  { name: 'Malavis' },
  { name: 'Maldyvai' },
  { name: 'Malis' },
  { name: 'Malta' },
  { name: 'Marianos šiaurinės salos' },
  { name: 'Marokas' },
  { name: 'Martinika' },
  { name: 'Maršalo salos' },
  { name: 'Mauricijus' },
  { name: 'Mauritanija' },
  { name: 'Meksika' },
  { name: 'Meno sala' },
  { name: 'Mergelių salos (JAV)' },
  { name: 'Mianmaras' },
  { name: 'Mikronezijos Federacinės Valstijos' },
  { name: 'Moldavija' },
  { name: 'Monakas' },
  { name: 'Mongolija' },
  { name: 'Montseratas' },
  { name: 'Mozambikas' },
  { name: 'Namibija' },
  { name: 'Naujoji Kaledonija' },
  { name: 'Naujoji Zelandija' },
  { name: 'Nauru' },
  { name: 'Nepalas' },
  { name: 'Nyderlandai' },
  { name: 'Nyderlandų Antilai' },
  { name: 'Nigerija' },
  { name: 'Nigeris' },
  { name: 'Nikaragva' },
  { name: 'Niujė' },
  { name: 'Norfolkas' },
  { name: 'Norvegija' },
  { name: 'Omanas' },
  { name: 'Padniestrė' },
  { name: 'Pakistanas' },
  { name: 'Palau' },
  { name: 'Palestina' },
  { name: 'Panama' },
  { name: 'Papua Naujoji Gvinėja' },
  { name: 'Paragvajus' },
  { name: 'Peru' },
  { name: 'Pietų Afrikos Respublika' },
  { name: 'Pietų Džordžija ir Pietų Sandvičo salos' },
  { name: 'Pietų Korėja' },
  { name: 'Pietų Osetija' },
  { name: 'Pitkerno salos' },
  { name: 'Portugalija' },
  { name: 'Prancūzijos Gviana' },
  { name: 'Prancūzijos Polinezija' },
  { name: 'Prancūzija' },
  { name: 'Prancūzijos Pietų ir Antarkties sritys' },
  { name: 'Puerto Rikas' },
  { name: 'Pusiaujo Gvinėja' },
  { name: 'Reunionas' },
  { name: 'Ruanda' },
  { name: 'Rumunija' },
  { name: 'Rusija' },
  { name: 'Rytų Timoras' },
  { name: 'Saliamono salos' },
  { name: 'Salvadoras' },
  { name: 'Samoa' },
  { name: 'San Marinas' },
  { name: 'San Tomė ir Prinsipė' },
  { name: 'Saudo Arabija' },
  { name: 'Seišeliai' },
  { name: 'Sen Pjeras ir Mikelonas' },
  { name: 'Senegalas' },
  { name: 'Sent Kitsas ir Nevis' },
  { name: 'Sent Lusija' },
  { name: 'Sent Vinsentas ir Grenadinai' },
  { name: 'Serbija' },
  { name: 'Siera Leonė' },
  { name: 'Sylendas' },
  { name: 'Singapūras' },
  { name: 'Sirija' },
  { name: 'Slovakija' },
  { name: 'Slovėnija' },
  { name: 'Somalis' },
  { name: 'Somalilandas' },
  { name: 'Sudanas' },
  { name: 'Suomija' },
  { name: 'Surinamas' },
  { name: 'Svalbardas' },
  { name: 'Svazilandas' },
  { name: 'Šiaurės Korėja' },
  { name: 'Šri Lanka' },
  { name: 'Šventoji Elena' },
  { name: 'Švedija' },
  { name: 'Šveicarija' },
  { name: 'Tadžikija' },
  { name: 'Tailandas' },
  { name: 'Taivanas' },
  { name: 'Tanzanija' },
  { name: 'Terksas ir Kaikosas' },
  { name: 'Tibetas' },
  { name: 'Togas' },
  { name: 'Tokelau' },
  { name: 'Tonga' },
  { name: 'Trinidadas ir Tobagas' },
  { name: 'Tristanas da Kunja' },
  { name: 'Tunisas' },
  { name: 'Turkija' },
  { name: 'Turkmėnija' },
  { name: 'Turkų Kipras' },
  { name: 'Tuvalu' },
  { name: 'Uganda' },
  { name: 'Ukraina' },
  { name: 'Urugvajus' },
  { name: 'Uzbekija' },
  { name: 'Vakarų Sachara' },
  { name: 'Vanuatu' },
  { name: 'Vatikanas' },
  { name: 'Velykų sala' },
  { name: 'Venesuela' },
  { name: 'Vengrija' },
  { name: 'Vietnamas' },
  { name: 'Vokietija' },
  { name: 'Volisas ir Futuna' },
  { name: 'Zambija' },
  { name: 'Zimbabvė' }
]
